07 add avatar
js-tasks-ru/htmlcss-20240913_dimonnwc3 pull request #16
Opened 2024-10-05 14:52 UTC by dimonnwc3

2024-10-05 14:53 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-05 16:20 UTC, GSemikozov requested changes

2024-10-05 16:20 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  object-fit: contain;
все-таки cover

2024-10-06 15:04 UTC, GSemikozov approved these changes

2024-10-06 15:04 UTC, merged