07 add header logo
js-tasks-ru/htmlcss-20240913_dimonnwc3 pull request #19
Opened 2024-10-05 15:25 UTC by dimonnwc3

2024-10-05 15:25 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-05 16:23 UTC, GSemikozov requested changes

2024-10-05 16:23 UTC, GSemikozov commented on components/header/header.css
> +  display: flex;
точно надо блочным делать?

2024-10-05 16:23 UTC, GSemikozov commented on index.html
> +              src="./assets/images/logo.webp"
в целом нет смыла, можно сразу свг

2024-10-05 17:52 UTC, dimonnwc3 commented on index.html
> +              src="./assets/images/logo.webp"
изменил на svg, но не добавил в спрайт, т.к спрайт еще в другом PR находиться

2024-10-06 15:05 UTC, GSemikozov requested changes

2024-10-06 15:05 UTC, GSemikozov commented on components/header/header.css
> +  margin: 0 auto;
точно надо?

2024-10-06 15:05 UTC, GSemikozov commented on components/header/header.css
> +  object-fit: contain;
точно надо? или - точно contain?

2024-10-06 18:10 UTC, dimonnwc3 commented on components/header/header.css
> +  margin: 0 auto;
не уверен, что понимаю, как это лучше сделать
но пришла еще идея с абсолютным позиционированием

2024-10-07 10:18 UTC, GSemikozov approved these changes

2024-10-07 10:18 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-10-07 10:18 UTC, GSemikozov requested changes
конфликт

2024-10-07 13:07 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-11 15:00 UTC, GSemikozov approved these changes

2024-10-11 15:00 UTC, merged