07 add and use svg sprite
js-tasks-ru/htmlcss-20240913_dimonnwc3 pull request #20
Opened 2024-10-05 15:49 UTC by dimonnwc3

2024-10-05 15:49 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-05 16:22 UTC, GSemikozov requested changes

2024-10-05 16:22 UTC, GSemikozov commented on assets/css/main.css
> +.icon {
как отдельный компонент

2024-10-05 17:38 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-05 17:42 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-06 15:05 UTC, GSemikozov approved these changes

2024-10-06 15:05 UTC, merged