08 add checkbox
js-tasks-ru/htmlcss-20240913_dimonnwc3 pull request #22
Opened 2024-10-08 13:28 UTC by dimonnwc3

2024-10-11 15:10 UTC, GSemikozov requested changes

2024-10-11 15:10 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  border: 1px solid var(--primary);
а бордер лейблу точно нужен?)

2024-10-12 07:05 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-12 07:30 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-13 07:30 UTC, GSemikozov approved these changes

2024-10-13 07:30 UTC, merged