09 add burger-menu
js-tasks-ru/htmlcss-20240913_dimonnwc3 pull request #25
Opened 2024-10-12 14:29 UTC by dimonnwc3

2024-10-12 14:30 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-13 07:32 UTC, GSemikozov requested changes

2024-10-13 07:32 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__menu {
везде надо поменять имя блока - .burger-menu

2024-10-13 07:32 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  position: fixed;
лишнее

2024-10-13 07:32 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  transition: transform 250ms ease-in;
лишнее

2024-10-13 07:32 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.dark-mode {
реализовано как отдельный блок, соответственно здесь располагать - неправильно. Да и в общем-то верстать переключалку тему здесь не нужно

2024-10-13 07:32 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +    <button class="burger__menu__open" id="burger-menu-open">Open</button>
это не элемент блока

2024-10-13 12:43 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-13 12:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-14 04:24 UTC, GSemikozov approved these changes

2024-10-14 04:24 UTC, merged